# Generated by Django 5.1.2 on 2024-10-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='max_views',
            field=models.IntegerField(default=1),
        ),
    ]
